### ISSUE TITLE
Batch usage

### ISSUE THREAD

**Issue by mackworth** [fflewddur/tivolibre#14]
Thanks for the great work on this; I'm trying to migrate to tivolibre from tivodecode, and I'm having some trouble. Specifically, I'm trying to invoke tivolibre as a subtask using a piped command line to stdout for the output video. 
First, text output seems to be going to stdout as well (e.g. -d), rather than to stderr, which means that it gets mixed into the video stream. Is there a different way to invoke, or could the text be redirected?
Secondly, is there any way to tell if there was a an Invalid MAK used versus other failures?  (tivodecode literally puts "Invalid MAK" in the error log.) I assume if the conversion fails, then it returns an exit code greater than 0. Is there a list of exit codes?

**Comment by fflewddur** [comment]
Thanks for the patch! I'm not sure what's going on with skipBytes(), but I'll look into it; I definitely don't want to be allocating new buffers and copying data into them in that method, as it gets called very frequently to simply advance the byte stream. I think the better way to do this is to use logback's properties file to output all log calls to stderr, but I need to look into that more.

As for identifying invalid MAKs, no, I don't believe that's possible with TS files (tivodecode only supports this feature for PS files). However, TivoLibre will remember your MAK, so you shouldn't need to worry about making a typo each time you run the problem; it will always default to the last MAK passed with the -m parameter.

**Comment by mackworth** [comment]
In my testing, I only saw skipBytes being called once per stream, and for relatively small amounts; not surprising, as presumably most of the file wants to be kept!  The issue is that you can't seek on stdIn; apparently it's supposed to implement skipBytes on a stream with a read/ignore process underneath, but many implementations don't do that. I looked into conditionally doing it only on stdIn, but by the time you're down to that level, it's already been wrapped.

The XML approach for logback would probably be better; I assumed from the lack of an XML file that you didn't want to use that approach. 

After my original note, I spent some time and reversed out how tivodecode does the checking (and almost added it in), and found the same thing. Surely there's some similar structure in TS that one could look for to detect if garbage is being generated?

On the MAK, I'll be wrapping tivolibre in my UI, but the issue is I want to be able to tell the user if they mis-entered the MAK (versus just a damaged file).

**Comment by fflewddur** [comment]
Ah, you're right, skipBytes is only called once per video stream, so this should be a good fix. Could you let me know the reference you found for not using skipBytes on stdin? I want to document this so that I don't look at it again in 6 months and think "Why are we copying buffers? Let's just call skipBytes()" and change it back. I haven't found anything that says this is bad practice, as opposed to an exception that I should be handling in the skipBytes() method :)

For what it's worth, I also can't replicate the IOException on either my Mac OS X or Windows machines, both running the latest Oracle JDK.

As for validating the user's MAK, one solution is to try connecting to the TiVo, since it'll let you know if the MAK is invalid. This is approach I use for Archivo.

**Comment by mackworth** [comment]
Well, in the [JavaSE docs for DataInputStream](https://docs.oracle.com/javase/8/docs/api/java/io/DataInputStream.html), skipBytes says "Throws: IOException - if the contained input stream does not support seek". In most cases, it worked fine for me as well, it was only when I had a larger skip that it failed (e.g. 4 bytes worked fine, but 1542 bytes failed). My guess is that it's skipping when it has bytes "available" in the buffer, but throwing the exception when it would need to read more.

As another possible explanation, I note also: [stdin behaves differently when piped and when redirected](http://stackoverflow.com/questions/16482447/stdin-behaves-differently-when-piped-and-when-redirected).

Agreed on MAK; just a belt/suspenders thing.

**Comment by fflewddur** [comment]
PR merged with master, closing as resolved. Thanks!

**Comment by mackworth** [comment]
Thank you; it's an impressive piece of work!
