### ISSUE TITLE
pixelation/corruption of ts formatted tivo files

### ISSUE THREAD

**Issue by ejonesss** [fflewddur/tivolibre#16]
http://workupload.com/file/FlvfmPxo is a 100 meg sample of a ts formatted tivo file.

the file was downloaded from the tivo box in ts format.

the corruption happens every few seconds.

i am on a mac so i do not have access to directshow dump or videoredo.

the tivo/ts file will play ok on roxio video player but not decrypt properly

i used the command line version of the latest  tivo-libre-0.7.2.jar and it still pixelates.

the problem is decrypting to mpg format

**Comment by fflewddur** [comment]
Thanks for reporting this, the latest commit fixed the problem. Assuming all of my test cases pass with the new build (it'll take about 12 hours to run the tests), I'll put out the official release tomorrow.
