### ISSUE TITLE
Cannot run version 0.7.4

### ISSUE THREAD

**Issue by arantius** [fflewddur/tivolibre#18]
Trying to `java -jar` the 0.7.4 release file produces an error.  Indeed:

```
$ unzip -p tivo-libre-0.7.4.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
$ unzip -p tivo-libre-0.7.3.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
Main-Class: net.straylightlabs.tivolibre.DecoderApp
```

The manifest doesn't declare the main class.

**Comment by fflewddur** [comment]
This is intentional; TivoDecoder.jar is the runnable JAR and includes the manifest file, while tivo-libre-x.y.jar is a library intended for developers to embed within their projects.

**Comment by arantius** [comment]
In that case update the readme to match?  (It still says "java -jar tivo-libre.jar".)

**Comment by fflewddur** [comment]
Ah, thanks, missed that! :)
